SELECT COLUMN_NAME, 
        COLUMN_TYPE,
        DATA_TYPE, 
        CHARACTER_MAXIMUM_LENGTH, 
        IS_NULLABLE, 
        COLUMN_DEFAULT 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Books' 
AND TABLE_NAME = 'books';
